# Generated by Django 4.0.8 on 2023-05-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soil_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltype',
            name='soil_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soil_type.soilimage'),
        ),
    ]
