# Generated by Django 4.0.8 on 2023-04-16 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('ph', models.FloatField()),
                ('ec', models.FloatField()),
                ('oc', models.FloatField()),
                ('s', models.FloatField()),
                ('zn', models.FloatField()),
                ('fe', models.FloatField()),
                ('cu', models.FloatField()),
                ('mn', models.FloatField()),
                ('b', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('soil_elements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soil_quality.soilelement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
