# Generated by Django 4.0.8 on 2023-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_specialist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='profileupgradeapplication',
            name='documents',
            field=models.FileField(upload_to='users/profile/upgard/None'),
        ),
    ]
