# Generated by Django 4.0.8 on 2023-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_specialist', '0002_filemodel_alter_profileupgradeapplication_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AlterField(
            model_name='profileupgradeapplication',
            name='documents',
            field=models.FileField(upload_to='users/profile/upgard/'),
        ),
        migrations.AlterField(
            model_name='profileupgradeapplication',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
