# Generated by Django 4.0.8 on 2023-05-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_specialist', '0003_delete_filemodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgricultureSpecialist',
        ),
    ]
