# Generated by Django 4.0.8 on 2023-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_agriculture_specialist',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
