# Generated by Django 4.0.8 on 2023-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image_user_is_agriculture_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/images/<django.db.models.fields.CharField>'),
        ),
    ]
