# Generated by Django 4.0.8 on 2023-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agriculture_specialist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
