# Generated by Django 4.0.8 on 2023-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearest_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurersuryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
